const utilsGiantWalls = {
  demoRoomWalls: {
    [utils.asGridCoord(7, 6)]: true, // DYNAMIC key naming. Return value becomes key name
    [utils.asGridCoord(8, 6)]: true,
    [utils.asGridCoord(7, 7)]: true,
    [utils.asGridCoord(8, 7)]: true,
  },
  scp1: {
    [utils.asGridCoord(1, 3)]: true, // top room left
    [utils.asGridCoord(1, 4)]: true,
    [utils.asGridCoord(2, 2)]: true, // top room top
    [utils.asGridCoord(3, 2)]: true,
    [utils.asGridCoord(4, 2)]: true,
    [utils.asGridCoord(5, 2)]: true,
    [utils.asGridCoord(6, 2)]: true,
    [utils.asGridCoord(7, 2)]: true,
    [utils.asGridCoord(9, 2)]: true,
    [utils.asGridCoord(10, 2)]: true,
    [utils.asGridCoord(11, 2)]: true,
    [utils.asGridCoord(12, 2)]: true,
    [utils.asGridCoord(13, 2)]: true,
    [utils.asGridCoord(14, 2)]: true,
    [utils.asGridCoord(15, 3)]: true, // top room right
    [utils.asGridCoord(15, 4)]: true,
    [utils.asGridCoord(2, 5)]: true, // top room B left
    [utils.asGridCoord(3, 5)]: true,
    [utils.asGridCoord(4, 5)]: true,
    [utils.asGridCoord(5, 5)]: true,
    [utils.asGridCoord(6, 5)]: true,
    [utils.asGridCoord(7, 5)]: true,
    [utils.asGridCoord(9, 5)]: true, // top room B right
    [utils.asGridCoord(10, 5)]: true,
    [utils.asGridCoord(11, 5)]: true,
    [utils.asGridCoord(12, 5)]: true,
    [utils.asGridCoord(13, 5)]: true,
    [utils.asGridCoord(14, 5)]: true,
    [utils.asGridCoord(7, 6)]: true, // first Corridor left
    [utils.asGridCoord(7, 7)]: true,
    [utils.asGridCoord(7, 8)]: true,
    [utils.asGridCoord(7, 9)]: true,
    [utils.asGridCoord(6, 10)]: true,
    [utils.asGridCoord(6, 11)]: true,
    [utils.asGridCoord(6, 14)]: true,
    [utils.asGridCoord(6, 15)]: true,
    [utils.asGridCoord(6, 16)]: true,
    [utils.asGridCoord(6, 17)]: true,
    [utils.asGridCoord(6, 18)]: true,
    [utils.asGridCoord(6, 19)]: true,
    [utils.asGridCoord(6, 20)]: true,
    [utils.asGridCoord(6, 21)]: true,
    [utils.asGridCoord(6, 22)]: true,
    [utils.asGridCoord(6, 23)]: true,
    [utils.asGridCoord(6, 12)]: true, // first Room Top
    [utils.asGridCoord(5, 12)]: true,
    [utils.asGridCoord(4, 12)]: true,
    [utils.asGridCoord(3, 12)]: true,
    [utils.asGridCoord(2, 12)]: true,
    [utils.asGridCoord(1, 13)]: true, // first Room Left
    [utils.asGridCoord(1, 14)]: true,
    [utils.asGridCoord(1, 15)]: true,
    [utils.asGridCoord(1, 16)]: true,
    [utils.asGridCoord(1, 17)]: true,
    [utils.asGridCoord(1, 18)]: true,
    [utils.asGridCoord(1, 19)]: true,
    [utils.asGridCoord(2, 20)]: true, // first Room Bottom
    [utils.asGridCoord(3, 20)]: true,
    [utils.asGridCoord(4, 20)]: true,
    [utils.asGridCoord(5, 20)]: true,
    [utils.asGridCoord(9, 6)]: true, // first Corridor Right
    [utils.asGridCoord(9, 7)]: true,
    [utils.asGridCoord(9, 8)]: true,
    [utils.asGridCoord(9, 9)]: true,
    [utils.asGridCoord(9, 10)]: true,
    [utils.asGridCoord(9, 11)]: true,
    [utils.asGridCoord(9, 14)]: true,
    [utils.asGridCoord(9, 15)]: true,
    [utils.asGridCoord(9, 16)]: true,
    [utils.asGridCoord(9, 17)]: true,
    [utils.asGridCoord(9, 18)]: true,
    [utils.asGridCoord(9, 19)]: true,
    [utils.asGridCoord(9, 20)]: true,
    [utils.asGridCoord(9, 21)]: true, // Second Corridor Top
    [utils.asGridCoord(10, 21)]: true,
    [utils.asGridCoord(11, 21)]: true,
    [utils.asGridCoord(12, 21)]: true,
    [utils.asGridCoord(13, 21)]: true,
    [utils.asGridCoord(15, 21)]: true,
    [utils.asGridCoord(16, 21)]: true,
    [utils.asGridCoord(17, 21)]: true,
    [utils.asGridCoord(18, 21)]: true,
    [utils.asGridCoord(7, 24)]: true, // Second Corridor Bottom
    [utils.asGridCoord(8, 24)]: true,
    [utils.asGridCoord(9, 24)]: true,
    [utils.asGridCoord(10, 24)]: true,
    [utils.asGridCoord(11, 24)]: true,
    [utils.asGridCoord(12, 24)]: true,
    [utils.asGridCoord(13, 24)]: true,
    [utils.asGridCoord(14, 24)]: true,
    [utils.asGridCoord(15, 24)]: true,
    [utils.asGridCoord(16, 24)]: true,
    [utils.asGridCoord(17, 24)]: true,
    [utils.asGridCoord(18, 24)]: true,
    [utils.asGridCoord(13, 17)]: true, // Second Room Left
    [utils.asGridCoord(13, 18)]: true,
    [utils.asGridCoord(13, 19)]: true,
    [utils.asGridCoord(13, 20)]: true,
    [utils.asGridCoord(12, 17)]: true,
    [utils.asGridCoord(11, 10)]: true,
    [utils.asGridCoord(11, 11)]: true,
    [utils.asGridCoord(11, 12)]: true,
    [utils.asGridCoord(11, 13)]: true,
    [utils.asGridCoord(11, 14)]: true,
    [utils.asGridCoord(11, 15)]: true,
    [utils.asGridCoord(11, 16)]: true,
    [utils.asGridCoord(12, 9)]: true, // Second Room Top
    [utils.asGridCoord(13, 9)]: true,
    [utils.asGridCoord(14, 9)]: true,
    [utils.asGridCoord(15, 9)]: true,
    [utils.asGridCoord(16, 9)]: true,
    [utils.asGridCoord(17, 9)]: true,
    [utils.asGridCoord(18, 9)]: true,
    [utils.asGridCoord(19, 10)]: true, // Second Room Right
    [utils.asGridCoord(19, 11)]: true,
    [utils.asGridCoord(19, 12)]: true,
    [utils.asGridCoord(19, 13)]: true,
    [utils.asGridCoord(19, 14)]: true,
    [utils.asGridCoord(19, 15)]: true,
    [utils.asGridCoord(19, 16)]: true,
    [utils.asGridCoord(18, 17)]: true, // Second Room Bottom
    [utils.asGridCoord(17, 17)]: true,
    [utils.asGridCoord(16, 17)]: true,
    [utils.asGridCoord(15, 11)]: true, // Second Room Col
    [utils.asGridCoord(15, 12)]: true,
    [utils.asGridCoord(15, 13)]: true,
    [utils.asGridCoord(15, 14)]: true,
    [utils.asGridCoord(15, 15)]: true,
    [utils.asGridCoord(15, 16)]: true,
    [utils.asGridCoord(15, 17)]: true,
    [utils.asGridCoord(15, 18)]: true,
    [utils.asGridCoord(15, 19)]: true,
    [utils.asGridCoord(15, 20)]: true,
  },
};
